import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Chat from "Y/components/Chat";

import { api } from "Y/utils/api";

interface FormData {
  name: string;
  text: string;
  imageUrl: string;
}

const Home: NextPage = () => {
  const [data, setData] = useState<FormData>({
    name: "",
    text: "",
    imageUrl: "",
  });

  //   const handelDescriptionChange = (value: string) => {
  //     setData({
  //       ...data,
  //       description: value,
  //     });
  //   };

  //   const handelTitleChange = (value: string) => {
  //     setData({
  //       ...data,
  //       title: value,
  //     });
  //   };
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const utils = api.useContext();

  const addNew = api.user.addMessage.useMutation({
    onMutate: (newPost) => {
      utils.user.getData.cancel();
      const prevData = utils.user.getData.getData();

      utils.user.getData.setData(undefined, ({ data }) => [...data, newPost]);
      return { prevData };
    },
    onError(err, newPost, ctx) {
      utils.user.getData.setData(undefined, ctx.prevData);
    },
    onSettled: () => {
      utils.user.getData.invalidate();
    },
  });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" flex h-[100vh] items-center justify-center bg-gradient-to-bl  from-red-200 via-red-300 to-yellow-200 text-gray-900">
        {/**
         * The type is defined and can be autocompleted
         * 💡 Tip: Hover over `data` to see the result type
         * 💡 Tip: Cxl+Click (or CTRL+Click) on `text` to go to the server definition
         * 💡 Tip: Secondary click on `text` and "Rename Symbol" to rename it both on the client & server
         */}
        {/* <h1>{result.data.text}</h1> */}
        <Chat />
      </div>
    </>
  );
};

export default Home;
